config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'movies#index'
  
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  
  resources :movie_statuses, only: %i[create update destroy]
  resources :password_resets, only: %i[new create edit update]

  resources :users, only: %i[new create show edit update] do
    get '/watched', to: 'users#watched'
    get '/uninterested', to: 'users#uninterested'
  end

  namespace :admin do
    root 'movies#index'
    get 'movies/api_search', to: 'movies#api_search'
    
    resources :movies, only: %i[index create show edit update destroy] do
      collection do
        get '/search', to: 'movies#search'
      end
    end
    resources :genres, only: %i[index new create edit update destroy]
  end
end

app/models/user.rb
# Schema Information
#
# Table name: movies
#
# name               :string not null
# email              :string not null uniqueness
# avatar             :string
# role               :integer
# crypted_password   :string
# salt               :string
#

class User < ApplicationRecord
  authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader

  has_many :movie_statuses, dependent: :destroy
  has_many :movies, through: :movie_statuses

  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true

  enum role: { general: 0, admin: 1 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Pagy::Backend

  before_action :require_login, only: %i[show watched uninterested edit update]
  before_action :set_user, only: %i[show edit update watched uninterested]
  before_action :set_movie_statuses, only: %i[show watched uninterested]

  def show
    @pagy, @watch_movies = pagy_array(movie_search_by_status(@movie_statuses, 'watch').order(updated_at: :asc), items: 2)
  end

  def watched
    @pagy, @watched_movies = pagy_array(movie_search_by_status(@movie_statuses, 'watched').order(updated_at: :asc), items: 2)
  end

  def uninterested
    @pagy, @uninterested_movies = pagy_array(movie_search_by_status(@movie_statuses, 'uninterested').order(updated_at: :asc), items: 2)
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_url, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :avatar, :role, :password, :password_confirmation)
  end

  def set_movie_statuses
    # current_userが登録しているmovie_statusesのデータを取得
    @movie_statuses = current_user.movie_statuses
  end

  def movie_search_by_status(movie_statuses, status)
    # movie_statusesのデータから、ステータスがstatusのものだけ取得し、movie_idを配列に保存
    movie_id_array = movie_statuses.where(status: status).map { |i| i['movie_id'] }

    # movie_idの配列でwhere検索
    Movie.where(id: movie_id_array)
  end
end

app/views/users/_form.html.erb
<div class="form-wrapper mx-auto text-center mb-5">
  <h1><%= t('users.new.title') %></h1>
  <%= simple_form_for @user, :html => { :class => 'mr-3 text-start' } do |f| %>
    <div class="form-group">
      <%= f.input :name, label_html: { class: 'mt-3' }, hint: t('simple_form.hints.user.name') %>
      <%= f.input :email, label_html: { class: 'mt-4' } %>
      <%= f.input :password, label_html: { class: 'mt-4' }, hint: t('simple_form.hints.user.password') %>
      <%= f.input :password_confirmation, label_html: { class: 'mt-4' } %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn btn-primary mt-4' %>
    </div>
  <% end %>
</div>

app/views/users/_profile_top.html.erb
<div class="d-flex">
  <div class="w-25 d-flex justify-content-center align-items-center">
    <%= image_tag "#{@user.avatar}", class: 'profile-image', size: '100x100' %>
  </div>
  <div class="profile-top d-block w-75 ms-3">
    <p class="fs-1 text-white"><%= @user.name %></p>
    <div class="d-flex">
      <p class="me-3"><%= link_to (t 'defaults.edit_profile'), edit_user_path(@user), class: 'text-white' %></p>
      <p><%= link_to (t 'defaults.logout'), logout_path, method: :delete, class: 'text-white' %></p>
    </div>
  </div>
</div>

app/views/users/_uninterested_movie.html.erb
<div class="infinite-scroll-area">
  <% if request.smart_phone? %>
    <div class="trailer">
      <iframe loading="lazy" src="https://www.youtube.com/embed/<%= uninterested_movie.trailer_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <%= uninterested_movie.title %>
    <div class="d-flex text-center fs-3 m-1">
      <%= link_to movie_status_path(id: current_user.id, movie_id: uninterested_movie.id, user_id: current_user.id, status: 'watch'), method: :put, local: true, class: 'watch col-4 border' do %>
        <i class="fas fa-plus-circle text-white"></i>
      <% end %>
      <%= link_to movie_status_path(id: current_user.id, movie_id: uninterested_movie.id, user_id: current_user.id, status: 'watched'), method: :put, local: true, class: 'watched col-4 border' do %>
        <i class="fas fa-check-circle text-white"></i>
      <% end %>
      <%= link_to movie_status_path(id: current_user.id, movie_id: uninterested_movie.id, user_id: current_user.id, status: 'uninterested'), method: :delete, local: true, class: 'uninterested col-4 border bg-warning' do %>
        <i class="fas fa-minus-circle text-white"></i>
      <% end %>
    </div>
  <% else %>
    <div class="d-flex">
      <div class="col-6 me-2">
        <div class="trailer">
          <iframe loading="lazy" src="https://www.youtube.com/embed/<%= uninterested_movie.trailer_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
      </div>
      <div class="col-6">
        <div class="h3 mt-3 ms-1">
          <%= uninterested_movie.title %>
        </div>
        <div class="d-flex text-center fs-3 m-1">
          <%= link_to movie_status_path(id: current_user.id, movie_id: uninterested_movie.id, user_id: current_user.id, status: 'watch'), method: :put, local: true, class: 'watch col-4 border' do %>
            <i class="fas fa-plus-circle text-white"></i>
          <% end %>
          <%= link_to movie_status_path(id: current_user.id, movie_id: uninterested_movie.id, user_id: current_user.id, status: 'watched'), method: :put, local: true, class: 'watched col-4 border' do %>
            <i class="fas fa-check-circle text-white"></i>
          <% end %>
          <%= link_to movie_status_path(id: current_user.id, movie_id: uninterested_movie.id, user_id: current_user.id, status: 'uninterested'), method: :delete, local: true, class: 'uninterested col-4 border bg-warning' do %>
            <i class="fas fa-minus-circle text-white"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_watch_movie.html.erb
<div class="infinite-scroll-area">
  <% if request.smart_phone? %>
    <div class="trailer">
      <iframe loading="lazy" src="https://www.youtube.com/embed/<%= watch_movie.trailer_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <%= watch_movie.title %>
    <div class="d-flex text-center fs-3 m-1">
      <%= link_to movie_status_path(movie_id: watch_movie.id, user_id: current_user.id), method: :delete, local: true, class: 'watch col-4 border bg-warning' do %>
        <i class="fas fa-plus-circle text-white"></i>
      <% end %>
      <%= link_to movie_status_path(movie_id: watch_movie.id, user_id: current_user.id, status: 'watched'), method: :put, local: true, class: 'watched col-4 border' do %>
        <i class="fas fa-check-circle text-white"></i>
      <% end %>
      <%= link_to movie_status_path(movie_id: watch_movie.id, user_id: current_user.id, status: 'uninterested'), method: :put, local: true, class: 'uninterested col-4 border' do %>
        <i class="fas fa-minus-circle text-white"></i>
      <% end %>
    </div>
  <% else %>
    <div class="d-flex">
      <div class="col-6 me-2">
        <div class="trailer">
          <iframe loading="lazy" src="https://www.youtube.com/embed/<%= watch_movie.trailer_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
      </div>
      <div class="col-6">
        <div class="h3 mt-3 ms-1">
          <%= watch_movie.title %>
        </div>
        <div class="d-flex text-center fs-3 m-1">
          <%= link_to movie_status_path(movie_id: watch_movie.id, user_id: current_user.id), method: :delete, local: true, class: 'watch col-4 border bg-warning' do %>
            <i class="fas fa-plus-circle text-white"></i>
          <% end %>
          <%= link_to movie_status_path(movie_id: watch_movie.id, user_id: current_user.id, status: 'watched'), method: :put, local: true, class: 'watched col-4 border' do %>
            <i class="fas fa-check-circle text-white"></i>
          <% end %>
          <%= link_to movie_status_path(movie_id: watch_movie.id, user_id: current_user.id, status: 'uninterested'), method: :put, local: true, class: 'uninterested col-4 border' do %>
            <i class="fas fa-minus-circle text-white"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_watched_movie.html.erb
<div class="infinite-scroll-area">
  <% if request.smart_phone? %>
    <div class="trailer">
      <iframe loading="lazy" src="https://www.youtube.com/embed/<%= watched_movie.trailer_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <%= watched_movie.title %>
    <div class="d-flex text-center fs-3 m-1">
      <%= link_to movie_status_path(id: current_user.id, movie_id: watched_movie.id, user_id: current_user.id, status: 'watch'), method: :put, local: true, class: 'watch col-4 border' do %>
        <i class="fas fa-plus-circle text-white"></i>
      <% end %>
      <%= link_to movie_status_path(id: current_user.id, movie_id: watched_movie.id, user_id: current_user.id), method: :delete, local: true, class: 'watched col-4 border bg-warning' do %>
        <i class="fas fa-check-circle text-white"></i>
      <% end %>
      <%= link_to movie_status_path(id: current_user.id, movie_id: watched_movie.id, user_id: current_user.id, status: 'uninterested'), method: :put, local: true, class: 'uninterested col-4 border' do %>
        <i class="fas fa-minus-circle text-white"></i>
      <% end %>
    </div>
  <% else %>
    <div class="d-flex">
      <div class="col-6 me-2">
        <div class="trailer">
          <iframe loading="lazy" src="https://www.youtube.com/embed/<%= watched_movie.trailer_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
      </div>
      <div class="col-6">
        <div class="h3 mt-3 ms-1">
          <%= watched_movie.title %>
        </div>
        <div class="d-flex text-center fs-3 m-1">
          <%= link_to movie_status_path(id: current_user.id, movie_id: watched_movie.id, user_id: current_user.id, status: 'watch'), method: :put, local: true, class: 'watch col-4 border' do %>
            <i class="fas fa-plus-circle text-white"></i>
          <% end %>
          <%= link_to movie_status_path(id: current_user.id, movie_id: watched_movie.id, user_id: current_user.id), method: :delete, local: true, class: 'watched col-4 border bg-warning' do %>
            <i class="fas fa-check-circle text-white"></i>
          <% end %>
          <%= link_to movie_status_path(id: current_user.id, movie_id: watched_movie.id, user_id: current_user.id, status: 'uninterested'), method: :put, local: true, class: 'uninterested col-4 border' do %>
            <i class="fas fa-minus-circle text-white"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="form-wrapper mx-auto text-center mb-5">
  <h1><%= t('.title') %></h1>
  <%= simple_form_for @user, :html => { :class => 'mr-3 text-start' } do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.input :name, label_html: { class: 'mt-3' } %>
      <%= f.input :email, label_html: { class: 'mt-3' } %>
      <%= image_tag @user.avatar.url, id: 'preview', class: 'profile-image mt-3', size: '50x50' %>
      <%= f.input :avatar, label_html: { class: 'form-label' }, input_html: { onchange: 'previewImage(preview)', class: 'form-control' } %>
      <%= f.input :avatar_cache, :as => :hidden %>
    </div>
    <div class="form-group mb-5 pb-5">
      <%= f.button :submit, class: 'btn btn-primary mt-3 mb-5' %>
    </div>
  <% end %>
</div>
<script>
function previewImage() {
    const target = this.event.target;
    const file = target.files[0];
    const reader  = new FileReader();
    reader.onloadend = function () {
        const preview = document.querySelector("#preview")
        if(preview) {
            preview.src = reader.result;
        }
    }
    if (file) {
        reader.readAsDataURL(file);
    }
}
</script>

app/views/users/new.html.erb
<% content_for(:title, t('.title')) %>
<%= render 'form', user: @user %>
<% if request.smart_phone? %>
  <div class="row align-items-center text-center">
    <div class="col-6">
      <%= link_to '利用規約', page_path('terms'), class: 'text-white' %>
    </div>
    <div class="col-6">
      <%= link_to 'プライバシーポリシー', page_path('privacy_policy'), class: 'text-white' %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<% content_for(:title, t('.title')) %>
<%= render 'profile_top' %>
<div class="d-flex text-center fs-1 mt-3">
  <%= link_to user_path(@user), class: 'col-4 border bg-warning' do %>
    <i class="fas fa-plus-circle text-white"></i>
    <span class="fs-5 text-white align-middle">観たい</span>
  <% end %>
  <%= link_to user_watched_path(@user), class: 'col-4 border' do %>
    <i class="fas fa-check-circle text-white"></i>
    <span class="fs-5 text-white align-middle">観た</span>
  <% end %>
  <%= link_to user_uninterested_path(@user), class: 'col-4 border' do %>
    <i class="fas fa-minus-circle text-white"></i>
    <span class="fs-5 text-white align-middle">興味なし</span>
  <% end %>
</div>
<%= render partial: 'watch_movie', collection: @watch_movies %>
<div class="d-none">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>
<%= javascript_pack_tag "infinite-scroll" %>

app/views/users/uninterested.html.erb
<% content_for(:title, t('.title')) %>
<%= render 'profile_top' %>
<div class="d-flex text-center fs-1 mt-3">
  <%= link_to user_path(@user), class: 'col-4 border' do %>
    <i class="fas fa-plus-circle text-white"></i>
    <span class="fs-5 text-white align-middle">観たい</span>
  <% end %>
  <%= link_to user_watched_path(@user), class: 'col-4 border' do %>
    <i class="fas fa-check-circle text-white"></i>
    <span class="fs-5 text-white align-middle">観た</span>
  <% end %>
  <%= link_to user_uninterested_path(@user), class: 'col-4 border bg-warning' do %>
    <i class="fas fa-minus-circle text-white"></i>
    <span class="fs-5 text-white align-middle">興味なし</span>
  <% end %>
</div>
<%= render partial: 'uninterested_movie', collection: @uninterested_movies %>
<div class="d-none">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>
<%= javascript_pack_tag "infinite-scroll" %>

app/views/users/watched.html.erb
<% content_for(:title, t('.title')) %>
<%= render 'profile_top' %>
<div class="d-flex text-center fs-1 mt-3">
  <%= link_to user_path(@user), class: 'col-4 border' do %>
    <i class="fas fa-plus-circle text-white"></i>
    <span class="fs-5 text-white align-middle">観たい</span>
  <% end %>
  <%= link_to user_watched_path(@user), class: 'col-4 border bg-warning' do %>
    <i class="fas fa-check-circle text-white"></i>
    <span class="fs-5 text-white align-middle">観た</span>
  <% end %>
  <%= link_to user_uninterested_path(@user), class: 'col-4 border' do %>
    <i class="fas fa-minus-circle text-white"></i>
    <span class="fs-5 text-white align-middle">興味なし</span>
  <% end %>
</div>
<%= render partial: 'watched_movie', collection: @watched_movies %>
<div class="d-none">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>
<%= javascript_pack_tag "infinite-scroll" %>