config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'movies#index'
  
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  
  resources :movie_statuses, only: %i[create update destroy]
  resources :password_resets, only: %i[new create edit update]

  resources :users, only: %i[new create show edit update] do
    get '/watched', to: 'users#watched'
    get '/uninterested', to: 'users#uninterested'
  end

  namespace :admin do
    root 'movies#index'
    get 'movies/api_search', to: 'movies#api_search'
    
    resources :movies, only: %i[index create show edit update destroy] do
      collection do
        get '/search', to: 'movies#search'
      end
    end
    resources :genres, only: %i[index new create edit update destroy]
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom bg-dark footer-pc'>
  <hr>
  <% if request.smart_phone? %>
    <% if logged_in? %>
      <div class="row align-items-center ms-4 me-4">
        <div class="col-4 text-center fs-7">
          <%= link_to root_path do %>
            <i class="fa fa-home fa-4x" style="color: white;"></i>
          <% end %>
        </div>
        <div class="col-4 text-center">
          <%= link_to user_path(current_user), class: 'text-light' do %>
            <div>
              <%= image_tag "#{current_user.avatar}", class: 'profile-image', size: '40x40' %>
            </div>
            <div>
              <%= current_user.name %>
            </div>
          <% end %>
        </div>
        <div class="col-4 text-center">
          <%= link_to page_path('information') do %>
            <i class="fas fa-info-circle fa-2x" style="color: white;"></i>
          <% end %>
        </div>
      </div>
    <% else %>
      <% unless request.path.include?("new") || request.path.include?("login") %>
        <div class="row mb-2 ms-3 me-3">
          <div class="col-1"></div>
          <div class="col-5 text-center fs-5">
            <%= link_to login_path, class: 'text-light' do %>
              <%= (t 'defaults.login') %>
            <% end %>
          </div>
          <div class="col-5 text-center fs-5">
            <%= link_to new_user_path, class: 'text-danger' do %>
              <%= (t 'users.new.title') %>
            <% end%>
          </div>
          <div class="col-1 text-center">
            <%= link_to page_path('information') do %>
              <i class="fas fa-info-circle fa-2x" style="color: white;"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="d-flex align-items-center">
      <div class="d-flex align-items-center w-50 ms-3">
        <%= link_to 'https://www.themoviedb.org/', target: :_blank, rel: "noopener noreferrer" do %>
          <%= image_tag 'logo_tmdb.svg', size: '50x50', class: 'me-3' %>
        <% end %>
        このサービスはTMDB APIを使用しており、<br />
        TMDBによって承認または認定されています。
      </div>
      <div class="d-flex flex-row-reverse w-50">
        <span class="text-white-50 me-3">© シネマト</span>
        <%= link_to 'プライバシーポリシー', page_path('privacy_policy'), class: 'text-white me-3' %>
        <%= link_to '利用規約', page_path('terms'), class: 'text-white me-3' %>
        <%= link_to 'お問い合わせ', page_path('contact'), class: 'text-white me-3' %>
      </div>
    </div>
  <% end %>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light bg-dark">
    <%= link_to root_path, class: 'navbar-brand ms-5 text-light fs-1  me-auto customize-font' do %>
      シネマト<span class="fs-6">次の「観たい」が見つかる</span>
    <% end %>
    <% if !request.smart_phone? %>
      <% if logged_in? %>
        <%= link_to user_path(current_user), class: 'd-flex align-items-center me-4 text-light' do %>
          <%= image_tag "#{current_user.avatar}", class: 'profile-image me-2', size: '50x50' %>
          <%= current_user.name %>
        <% end %>
      <% else %>
        <%= link_to login_path, class: 'd-flex me-4 text-light' do %>
          <%= (t 'defaults.login') %>
        <% end %>
        <%= link_to new_user_path, class: 'd-flex me-5 text-danger' do %>
          <%= (t 'users.new.title') %>
        <% end%>
      <% end %>
    <% end %>
</nav>