config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'movies#index'
  
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  
  resources :movie_statuses, only: %i[create update destroy]
  resources :password_resets, only: %i[new create edit update]

  resources :users, only: %i[new create show edit update] do
    get '/watched', to: 'users#watched'
    get '/uninterested', to: 'users#uninterested'
  end

  namespace :admin do
    root 'movies#index'
    get 'movies/api_search', to: 'movies#api_search'
    
    resources :movies, only: %i[index create show edit update destroy] do
      collection do
        get '/search', to: 'movies#search'
      end
    end
    resources :genres, only: %i[index new create edit update destroy]
  end
end

app/models/genre.rb
# Schema Information
#
# Table name: genres
#
# api_genre_id   :integer    not null uniqueness
# name           :string     not null uniqueness
# created_at     :datetime   not null
# updated_at     :datetime   not null
#

class Genre < ApplicationRecord
  has_many :movie_genres, dependent: :destroy
  has_many :movies, through: :movie_genres

  validates :api_genre_id, presence: true
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::BaseController
  before_action :set_genre, only: %i[edit update destroy]
  def index
    @genres = Genre.all.order(id: :asc)
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to new_admin_genre_path, success: t('.success')
    else
      flash.now['danger'] = t('.fail')
      render :new
    end
  end

  def edit; end

  def update
    if @genre.update(genre_params)
      redirect_to admin_genres_path, success: t('.success')
    else
      render :edit, danger: t('.fail')
    end
  end

  def destroy
    @genre.destroy!
    redirect_to admin_genres_path, success: t('.success')
  end

  private

  def genre_params
    params.require(:genre).permit(:api_genre_id, :name)
  end

  def set_genre
    @genre = Genre.find(params[:id])
  end
end

app/views/admin/genres/_form.html.erb
<%= simple_form_for [:admin, @genre], :html => { :class => 'mt-3' } do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.input :api_genre_id %>
    <%= f.input :name %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/genres/_genre.html.erb
<tr>
  <th scope="row"></th>
  <td><%= genre.id %></td>
  <td><%= genre.api_genre_id %></td>
  <td><%= genre.name %></td>
  <td class="align-middle"><%= link_to '編集', edit_admin_genre_path(genre), class: 'btn btn-warning' %></td>
  <td class="align-middle"><%= link_to '削除', admin_genre_path(genre), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %></td>
</tr>

app/views/admin/genres/edit.html.erb
<% content_for(:title, t('.title')) %>
<%= render 'form', { genre: @genre } %>

app/views/admin/genres/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="text-center mt-3">
  <%= link_to (t 'defaults.register'), new_admin_genre_path, class: 'btn btn-primary' %>
</div>
<% if @genres.present? %>
  <table class="table mt-3">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">id</th>
        <th scope="col">api_genre_id</th>
        <th scope="col">name</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <%= render @genres %>
    </tbody>
  </table>
<% else %>
  <p>ジャンルは登録されていません</p>
<% end %>

app/views/admin/genres/new.html.erb
<% content_for(:title, t('.title')) %>
<%= render 'form', { genre: @genre } %>