config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'movies#index'
  
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  
  resources :movie_statuses, only: %i[create update destroy]
  resources :password_resets, only: %i[new create edit update]

  resources :users, only: %i[new create show edit update] do
    get '/watched', to: 'users#watched'
    get '/uninterested', to: 'users#uninterested'
  end

  namespace :admin do
    root 'movies#index'
    get 'movies/api_search', to: 'movies#api_search'
    
    resources :movies, only: %i[index create show edit update destroy] do
      collection do
        get '/search', to: 'movies#search'
      end
    end
    resources :genres, only: %i[index new create edit update destroy]
  end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < Admin::BaseController
  include Pagy::Backend
  require 'net/http'
  require 'uri'
  require 'json'

  before_action :set_movie, only: %i[show edit update destroy]
  before_action :set_q, only: %i[index search]
  before_action :set_search_result, only: %i[api_search]

  def index
    @pagy, @movies = pagy(Movie.all.order(id: :desc))
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to admin_movies_api_search_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :api_search
    end
  end

  def show; end

  def edit; end

  def update
    if @movie.update(movie_params)
      redirect_to edit_admin_movie_path(@movie), success: t('.success')
    else
      render :edit, danger: t('.fail')
    end
  end

  def destroy
    @movie.destroy!
    redirect_to admin_movies_path, success: t('.success')
  end

  def search
    @movies = @q.result.order(user_score: :desc)
  end

  def api_search
    return if @search_result['results'].nil?

    detail_url = "https://api.themoviedb.org/3/movie/#{@search_result['results'][0]['id']}?api_key=fffa263e9395a32c7352e5ee7a5b8df3&language=ja-JP&append_to_response=videos"
    detail_uri = URI.parse(detail_url)
    detail_json = Net::HTTP.get(detail_uri)
    @detail_result = JSON.parse(detail_json)

    @movie = Movie.new(api_id: @detail_result['id'],
                          title: @detail_result['title'],
                          runtime: @detail_result['runtime'],
                          user_score: @detail_result['vote_average'] * 10,
                          release_date: @detail_result['release_date'],
                          overview: @detail_result['overview'],
                          poster_url: @detail_result['poster_path'])
    @movie.trailer_url = @detail_result['videos']['results'][0]['key'] if @detail_result['videos']['results'][0]

    3.times { @movie.movie_genres.build }
  end

  private

  def movie_params
    params.require(:movie).permit(:api_id,
                                  :title,
                                  :runtime,
                                  :user_score,
                                  :release_date,
                                  :overview,
                                  :poster_url,
                                  :trailer_url,
                                  movie_genres_attributes: %i[id movie_id genre_id])
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def set_q
    @q = Movie.ransack(params[:q])
  end

  def set_search_result
    query = URI.encode_www_form(q: params[:user_input].to_s).delete_prefix('q=')
    url = "https://api.themoviedb.org/3/search/movie?api_key=fffa263e9395a32c7352e5ee7a5b8df3&language=ja-JP&page=1&query=#{query}"
    uri = URI.parse(url)
    json = Net::HTTP.get(uri)
    @search_result = JSON.parse(json)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include Pagy::Backend

  def index
    # 全映画をユーザースコア順に並べて取得
    all_movies = Movie.all.order(user_score: :desc).order(id: :asc)
    # ブラウザを開き直したとき、最後に観た映画の次の映画から表示
    next_view_movies = if cookies['cinemat_movie_id']
                         # ブラウザを閉じる前、最後に観ていた映画を取得
                         last_viewed_movie = Movie.find(cookies['cinemat_movie_id'].to_i)
                         # 全映画の中から、last_viewed_movieの次から最後までのデータを取得し、Activerecord Relationに
                         all_movies[all_movies.index(last_viewed_movie) + 1..all_movies.index(all_movies.last)]
                       end

    # last_viewed_movieが最後のデータだったとき、next_view_moviesがカラになるのを防ぐ
    next_view_movies = all_movies if next_view_movies.blank?

    # 「観たい」「観た」「興味なし」に登録した映画を表示しない
    status_movies = if current_user
                      # current_userの映画ステータスデータを取得
                      movie_statuses = current_user.movie_statuses
                      # movie_statusesのmovie_idを配列に保存
                      movie_status_id_array = movie_statuses.map { |i| i['movie_id'] }

                      # movie_idの配列でwhere検索
                      Movie.where(id: movie_status_id_array)
                    end

                     # 未ログインユーザー x クッキーなし
    @pagy, @movies = if current_user.nil? && cookies['cinemat_movie_id'].nil?
                       pagy(all_movies, items: 2)
                     # 未ログインユーザー x クッキーあり
                     elsif current_user.nil? && cookies['cinemat_movie_id'].present?
                       pagy_array(next_view_movies, items: 2)
                     # ログインユーザー x クッキーなし
                     elsif current_user && cookies['cinemat_movie_id'].nil?
                       pagy_array(all_movies - status_movies, items: 2)
                     # ログインユーザー x クッキーあり
                     elsif current_user && cookies['cinemat_movie_id'].present?
                       pagy_array(next_view_movies - status_movies, items: 2)
                     end
  end
end

app/views/admin/movies/_movie.html.erb
<tr>
  <th scope="row"></th>
  <td><%= image_tag "https://image.tmdb.org/t/p/w1280/#{movie.poster_url}", height: '100px' %></td>
  <td class="align-middle"><%= movie.id %></td>
  <td class="align-middle"><%= movie.api_id %></td>
  <td class="align-middle"><%= movie.title %></td>
  <td class="align-middle"><%= movie.user_score %></td>
  <td class="align-middle"><%= link_to (t 'defaults.show'), admin_movie_path(movie), class: 'btn btn-success' %></td>
  <td class="align-middle"><%= link_to (t 'defaults.edit'), edit_admin_movie_path(movie), class: 'btn btn-warning' %></td>
  <td class="align-middle"><%= link_to (t 'defaults.delete'), admin_movie_path(movie), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %></td>
</tr>

app/views/admin/movies/_search_form.html.erb
<div class="d-flex justify-content-center align-items-center mt-3 ">
  <%= search_form_for @q, url: search_admin_movies_path, class: 'me-3' do |f| %>
    <%= f.search_field :title_cont %>
    <%= f.submit %>
  <% end %>
  <%= link_to (t 'defaults.register'), admin_movies_api_search_path, class: 'btn btn-primary' %>
</div>

app/views/admin/movies/api_search.html.erb
<div class="text-center mt-3">
  <p class="mr-3 fw-bold">The Movie Databaseから検索</p>
  <%= form_tag(admin_movies_api_search_path, method: :get) do %>
    <%= search_field_tag :user_input, nil, placeholder: 'Movie Title...' %>
    <%= submit_tag (t 'defaults.search') %>
  <% end %>
</div>
<%if params[:user_input].present? %>
  <hr>
  <p class="text-center fw-bold fs-3"><%= params[:user_input] %>　の検索結果</p>
  <%= content_tag(:p, 'この映画は登録済みです', class: 'text-center fw-bold fs-3 text-danger') if Movie.exists?(api_id: @movie.api_id) %>
  <div class="d-flex">
    <%= simple_form_for [:admin, @movie], html: { class: "me-3 w-25"} do |f| %>
      <div class="form-group">
        <%= f.input :api_id %>
        <%= f.input :title %>
        <%= f.input :runtime %>
        <%= f.input :user_score %>
        <%= f.input :release_date %>
        <%= f.input :overview %>
        <%= f.input :poster_url %>
        <%= f.input :trailer_url %>
        <%= f.fields_for :movie_genres do |ff| %>
          <%= ff.collection_select :genre_id, Genre.all, :id, :name %>
        <% end %>
        <%= f.button :submit, class: 'btn btn-primary mt-3' %>
      </div>
    <% end %>
    <div class="movie-data border w-75">
      <div class="d-flex">
        <div class="poster w-25">
          <% if @detail_result['poster_path'].present? %>
              <%= image_tag 'https://image.tmdb.org/t/p/w1280' + @detail_result['poster_path'],class: "card-img" %>
          <%end%>
        </div>
        <div class="poster w-75">
          <% if @detail_result['videos']['results'][0].present? %>
            <iframe src="https://www.youtube.com/embed/<%= @detail_result['videos']['results'][0]['key'] %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen class="w-100 h-100"></iframe>
          <%end%>
        </div>
      </div>
      <div class="detail p-3">
        <div class="d-flex">
          <div class="d-block border-right p-1 m-1 col-3">
            <% if @detail_result['id'].present? %>
              <p class="h5 text-center">api_id</p>
              <p class="text-center"><%= @detail_result['id'] %></p>
            <%end%>
          </div>
          <div class="d-block border-right p-1 m-1 col-3">
            <% if @detail_result['runtime'].present? %>
              <p class="h5 text-center">runtime</p>
              <p class="text-center"><%= @detail_result['runtime'] %></p>
            <%end%>
          </div>
          <div class="d-block border-right p-1 m-1 col-3">
            <% if @detail_result['vote_average'].present? %>
              <p class="h5 text-center">user_score</p>
              <p class="text-center"><%= @detail_result['vote_average'] * 10 %></p>
            <%end%>
          </div>
          <div class="d-block p-1 m-1 col-3">
            <% if @detail_result['release_date'].present? %>
              <p class="h5 text-center">release_date</p>
              <p class="text-center"><%= @detail_result['release_date'] %></p>
            <%end%>
          </div>
        </div>
        <hr>
        <% if @detail_result['title'].present? %>
          <p class="h3 ">title</p>
          <p><%= @detail_result['title'] %></p>
        <%end%>
        <hr>
        <% if @detail_result['genres'].present? %>
          <p class="h3">genres</p>
          <div class="d-flex">
            <% @detail_result['genres'].each do |genre| %>
              <p class="mr-2"><%= genre['name'] %></p>
            <% end %>
          </div>
        <%end%>
        <hr>
        <% if @detail_result['overview'].present? %>
          <p class="h3">overview</p>
          <p><%= @detail_result['overview'] %></p>
        <%end%>
      </div>
    </div>
  </div>
<%end%>

app/views/admin/movies/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="text-center mt-3">
  <%= link_to (t 'defaults.index'), admin_movies_path, class: 'btn btn-secondary' %>
  <%= link_to (t 'defaults.show'), admin_movie_path(@movie), class: 'btn btn-success' %>
  <%= link_to (t 'defaults.delete'), admin_movie_path(@movie), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
</div>
<%= simple_form_for [:admin, @movie], :html => { :class => 'mt-3' } do |f| %>
  <div class="form-group">
    <%= f.input :title, label_html: { class: 'mt-3' } %>
    <%= f.input :poster_url, label_html: { class: 'mt-3' } %>
    <%= f.input :trailer_url, label_html: { class: 'mt-3' } %>
    <%= f.input :api_id, label_html: { class: 'mt-3' } %>
    <%= f.input :release_date, discard_hour: true, discard_minute: true, label_html: { class: 'mt-3' } %>
    <%= f.input :user_score, label_html: { class: 'mt-3' } %>
    <%= f.input :overview, label_html: { class: 'mt-3' } %>
    <%= f.button :submit, (t 'defaults.update'), class: 'btn btn-primary mt-3' %>
  </div>
<% end %>

app/views/admin/movies/index.html.erb
<% content_for(:title, t('.title')) %>
<%= render 'search_form' %>
<%== pagy_bootstrap_nav(@pagy) %>
<% if @movies.present? %>
  <table class="table mt-3">
    <thead>
      <tr>
        <th></th>
        <th>poster</th>
        <th>id</th>
        <th>api_id</th>
        <th>title</th>
        <th>score</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @movies %>
    </tbody>
  </table>
<% else %>
  <p>映画は登録されていません</p>
<% end %>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/admin/movies/search.html.erb
<% content_for(:title, t('.title')) %>
<%= render 'search_form' %>
<% if @movies.present? %>
  <table class="table mt-3">
    <thead>
      <tr>
        <th></th>
        <th>poster</th>
        <th>id</th>
        <th>api_id</th>
        <th>title</th>
        <th>score</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @movies %>
    </tbody>
  </table>
<% else %>
  <p>映画は登録されていません</p>
<% end %>

app/views/admin/movies/show.html.erb
<div class="text-center mt-3">
  <%= link_to (t 'defaults.index'), admin_movies_path, class: 'btn btn-secondary' %>
  <%= link_to (t 'defaults.edit'), edit_admin_movie_path(@movie), class: 'btn btn-warning' %>
  <%= link_to (t 'defaults.delete'), admin_movie_path(@movie), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
</div>
<div class="movie-data mx-auto mt-3 border">
    <div class="d-flex">
      <div class="poster w-25">
        <%= image_tag "https://image.tmdb.org/t/p/w1280/#{@movie.poster_url}", class: "card-img" %>
      </div>
      <div class="poster w-75">
        <iframe src="https://www.youtube.com/embed/<%= @movie.trailer_url%>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen class="w-100 h-100"></iframe>
      </div>
    </div>
    <div class="detail p-3">
      <div class="d-flex">
        <div class="d-block border-right p-1 m-1 col-3">
          <p class="h5 text-center">api_id</p>
          <p class="text-center"><%= @movie.api_id %></p>
        </div>
        <div class="d-block border-right p-1 m-1 col-3">
          <p class="h5 text-center">runtime</p>
          <p class="text-center"><%= @movie.runtime %></p>
        </div>
        <div class="d-block border-right p-1 m-1 col-3">
          <p class="h5 text-center">user_score</p>
          <p class="text-center"><%= @movie.user_score %></p>
        </div>
        <div class="d-block p-1 m-1 col-3">
          <p class="h5 text-center">release_date</p>
          <p class="text-center"><%= @movie.release_date %></p>
        </div>
      </div>
      <hr>
        <p class="h3 ">title</p>
        <p><%= @movie.title %></p>
      <hr>
        <p class="h3">genres</p>
        <div class="d-flex">
          <% @movie.genres.each do |genre| %>
            <p class="mr-2"><%= genre.name %></p>
          <% end %>
        </div>
      <hr>
        <p class="h3">overview</p>
        <p><%= @movie.overview %></p>
    </div>
  </div>
</div>